name: expense_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: GTWalsheimPro-Bold
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
    - family: GTWalsheimPro-Medium
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Medium.ttf
    - family: GTWalsheimPro-Regular
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf
    - family: GTWalsheimPro-Light
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Light.ttf